version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workflowdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build:
      context: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - ./backend/.env.example
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq
      - redis

  worker:
    build:
      context: ./backend
    command: celery -A app.celery_app.celery worker --loglevel=info -Q default
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - ./backend/.env.example
    depends_on:
      - postgres
      - rabbitmq
      - redis

volumes:
  pgdata: